name = Aang
mainclass = furhatos.app.aang.AangSkill
version = 1.0.0
language = en-US
logLevel = INFO
requiresVersion = false
requiresCamera = false
requiresSpeaker = false
requiresMicrophone = false
requiresRecognizer = false
